<a href="https://colab.research.google.com/github/SumasreeD/Python-for-Data-Science-ML/blob/My_learnings/Python_for_data_analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Numpy Arrays
import numpy as np

my_list=[1,2,3,4,5,6]
np.array(my_list)


array([1, 2, 3, 4, 5, 6])

In [ ]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#It creates an instance of ndarray with evenly spaced values and returns the reference to it.
#numpy.arange([start,stop, [step, ], dtype=None)
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,2,float)

array([1., 3., 5., 7., 9.])

In [ ]:
#Return a new array of given shape and type, filled with zeros.
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty(2) #return a new array of given shape and type, without initializing entries.

array([2.00000000e+000, 6.95319691e-310])

In [ ]:
np.empty((2,2))

array([[5.04184970e-310, 0.00000000e+000],
       [5.73116149e-322, 6.94581732e-310]])

In [ ]:
#Return a new array of given shape and type, filled with ones.
np.ones(3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere
#+ve refers upper triangle and -ve refers lower triangle
np.eye(3)
np.eye(4,k=1)
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.linspace(5,3,10)

array([5.        , 4.77777778, 4.55555556, 4.33333333, 4.11111111,
       3.88888889, 3.66666667, 3.44444444, 3.22222222, 3.        ])

In [ ]:
# Random function
np.random.rand(5)

array([0.56775517, 0.7937963 , 0.03988093, 0.32053137, 0.889661  ])

In [ ]:
np.random.rand(5,2)

array([[0.00380641, 0.45868248],
       [0.50499248, 0.25324612],
       [0.33393526, 0.50833975],
       [0.26591817, 0.11239006],
       [0.11592435, 0.50035615]])

In [ ]:
np.random.randn(2)
np.random.randn(2,3)

array([[-1.63851346,  0.33039083, -0.65841495],
       [ 1.06149503, -0.28851352, -1.37815733]])

In [ ]:
np.random.randint(1,100)

89

In [ ]:
np.random.randint(1,100,10)

array([57, 51, 84, 53, 32, 89, 19, 84, 36, 70])

**NUMPY OPERATIONS:**


In [7]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr+arr # adding the values

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
# we can also perform scalar functions on numpy

arr+100 # adds 100  to each element

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [12]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [13]:
arr/0 # gives the error warning

<ipython-input-13-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
<ipython-input-13-39e2cbdaf753>:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [14]:
arr/arr

<ipython-input-14-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
1/arr

<ipython-input-15-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [16]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [17]:
np.sqrt(arr) # give sthe square root of each element in array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [18]:
np.exp(arr) # exponential values

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [20]:
np.max(arr)
     #or
arr.max()

10

In [21]:
# we can also perform metric functions

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [22]:
np.log(arr)

<ipython-input-22-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])